skip network validation when studio key not defined

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -33,7 +33,12 @@ jobs:
         run: bun generate:types
 
       - name: Validate logic
-        run: bun validate:networks
+        run: |
+          if [ -z "${{ env.THEGRAPH_STUDIO_KEY }}" ]; then
+            echo "Error: secrets.THEGRAPH_STUDIO_KEY is not set - can't validate networks"
+            exit 1
+          fi
+          bun validate:networks
 
       - name: Generate registry
         run: bun generate:public
@@ -99,5 +104,5 @@ jobs:
             - ${{ env.REGISTRY_ROOT_URL }}/TheGraphNetworksRegistrySchema_v${{ env.MAJOR }}_${{ env.MINOR }}.json
 
     env:
-      THEGRAPH_STUDIO_KEY: ${{ vars.THEGRAPH_STUDIO_KEY }}
+      THEGRAPH_STUDIO_KEY: ${{ secrets.THEGRAPH_STUDIO_KEY }}
       REGISTRY_ROOT_URL: "https://graphregistry.pages.dev"
